#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}
MINICONDA_VERSION=${IMAGE_TAG:0:1}

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg MINICONDA_VERSION=$MINICONDA_VERSION \
             --build-arg PYTHON_VERSION=$IMAGE_TAG \
             -t $IMAGE_NAME .