#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

MINICONDA_RELEASE=${IMAGE_TAG%-*}
PYTHON_VERSION=${IMAGE_TAG#*-}
MINICONDA_VERSION=${PYTHON_VERSION:0:1}

# Trigger build
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg MINICONDA_VERSION=$MINICONDA_VERSION \
             --build-arg MINICONDA_RELEASE=$MINICONDA_RELEASE \
             --build-arg PYTHON_VERSION=$PYTHON_VERSION \
             -t $DOCKER_REPO:${DOCKER_TAG//,/ -t $DOCKER_REPO:} .