#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.
IMAGE_REPO=${IMAGE_NAME%:*}
IMAGE_TAG=${IMAGE_NAME#*:}

# Retag to latest
if [ "$IMAGE_TAG" = "3.6" ]; then
    docker tag $IMAGE_NAME ${IMAGE_REPO}:latest
    docker push ${IMAGE_REPO}:latest
    docker tag $IMAGE_NAME ${IMAGE_REPO}:3
    docker push ${IMAGE_REPO}:3
fi

if [ "$IMAGE_TAG" = "2.7" ]; then
	docker tag $IMAGE_NAME ${IMAGE_REPO}:2
    docker push ${IMAGE_REPO}:2
fi